luwaidev/CSC207-Project

Project/src/interface_adapter/bet_prediction/BetController.java, Project/src/interface_adapter/bet_prediction/BetPresenter.java, Project/src/use_case/bet_predictor/BetInputBoundary.java, Project/src/use_case/bet_predictor/BetInputData.java, Project/src/use_case/bet_predictor/BetInteractor.java, Project/src/use_case/bet_predictor/BetOutputBoundary.java, Project/src/use_case/bet_predictor/BetOutputData.java
Implemented controller, input output data and boundary, set up presenter and interactor.
=> Team prediction(Use Case1) 

Project/.idea/misc.xml, Project/.idea/vcs.xml, Project/src/app/Main.java, Project/src/app/SignupUseCaseFactory.java, Project/src/data_access/FileUserDataAccessObject.java, Project/src/interface_adapter/Menu/MenuViewModel.java, Project/src/interface_adapter/bet_prediction/BetPredictionState.java, Project/src/interface_adapter/bet_prediction/BetPredictionViewModel.java, Project/src/interface_adapter/clear_users/ClearController.java, Project/src/interface_adapter/clear_users/ClearPresenter.java, Project/src/interface_adapter/menu/MenuViewModel.java, Project/src/use_case/clear_users/ClearInputBoundary.java, Project/src/use_case/clear_users/ClearInputData.java, Project/src/use_case/clear_users/ClearInteractor.java, Project/src/use_case/clear_users/ClearOutputBoundary.java, Project/src/use_case/clear_users/ClearOutputData.java, Project/src/use_case/clear_users/ClearUserDataAccessInterface.java, Project/src/use_case/signup/SignupInputData.java, Project/src/view/BetPredictionView.java, Project/src/view/LoginView.java, Project/src/view/MenuView.java, Project/src/view/SignupView.java
- edited app/main to display bet predictor view
- implemented bet predictor view with view model and state
- imported clear users code
=> Implement Basic UI for Bet Prediction

Project/src/use_case/bet_predictor/BetInteractor.java, Project/src/use_case/bet_predictor/BetTeamDataAccessInterface.java
will add more once DAO is done, pushing it for now
=> general layout for interactor and DAI

Project/src/app/LoginUseCaseFactory.java, Project/src/app/Main.java, Project/src/app/MenuUseCaseFactory.java, Project/src/interface_adapter/login/LoginController.java, Project/src/interface_adapter/login/LoginPresenter.java, Project/src/interface_adapter/login/LoginViewModel.java, Project/src/interface_adapter/menu/MenuController.java, Project/src/interface_adapter/menu/MenuPresenter.java, Project/src/interface_adapter/menu/MenuState.java, Project/src/interface_adapter/menu/MenuViewModel.java, Project/src/interface_adapter/signup/SignupController.java, Project/src/interface_adapter/signup/SignupPresenter.java, Project/src/interface_adapter/signup/SignupViewModel.java, Project/src/use_case/login/LoginInputBoundary.java, Project/src/use_case/login/LoginInteractor.java, Project/src/use_case/menu/MenuInputBoundary.java, Project/src/use_case/menu/MenuInteractor.java, Project/src/use_case/menu/MenuOutputBoundary.java, Project/src/use_case/signup/SignupInputBoundary.java, Project/src/use_case/signup/SignupInteractor.java, Project/src/use_case/signup/SignupOutputBoundary.java, Project/src/view/LoggedInView.java, Project/src/view/LoginView.java, Project/src/view/MenuView.java, Project/src/view/SignupView.java, README.md
- implement menu use case factory
- Implement menu controller, use case interactor, menu presenter
=> implement menu view

Project/src/use_case/player_bet_predictor/PlayerInputBoundary.java, Project/src/use_case/player_bet_predictor/PlayerInputData.java, Project/src/use_case/player_bet_predictor/PlayerInteractor.java, Project/src/use_case/player_bet_predictor/PlayerOutputBoundary.java, Project/src/use_case/player_bet_predictor/PlayerOutputData.java, Project/src/use_case/player_bet_predictor/PlayerTeamDataAccessInterface.java
For other feature allowing user to place bets on points a player will score in next game, added:
- Input/Output Data
- Input/Output Boundary
- started interactor and DAO, will complete as we progress further.
=> Player Bets

Project/src/data_access/PlayerDataAccessObject.java, Project/src/entity/Player.java
Created Player Entity and created Player data DAO (using API)
=> Player data DAO and Player Entity

Project/src/app/Main.java, Project/src/entity/BetHistory.java, Project/src/interface_adapter/bet_history/BetHistoryViewModel.java, Project/src/use_case/bet_history/BetHistoryInteractor.java
BetHistory Interactor added, saveToHistory method complete, able to now update the bethistory entity, bethistory entity methods added to store incoming bets.
=> BetHistory Interactor

Project/src/interface_adapter/bet_prediction/BetPredictionPresenter.java, Project/src/use_case/bet_predictor/BetInteractor.java
Added the case in which the user types in an invalid team name for the presenter
=> added another case for bet prediction presenter

Project/src/interface_adapter/player_bets/PlayerController.java, Project/src/interface_adapter/player_bets/PlayerPredictionState.java, Project/src/interface_adapter/player_bets/PlayerPredictionViewModel.java, Project/src/interface_adapter/player_bets/PlayerPresenter.java, Project/src/use_case/player_bet_predictor/PlayerInteractor.java, Project/src/use_case/player_bet_predictor/PlayerOutputBoundary.java
(1) forgot to add classes for interface adapter initially. they aren't fully complete yet, but there.
(2) began interactor -> some changes will be made to player and/or the DAO for player, so it is also subject to change
=> added classes for interface adapter + began interactor

Project/src/data_access/PlayerDataAccessObject.java
This will allow user to enter a first and last name into the user interface and assign an ID to a player which will let us find stats for that player
=> finished id search for player in player DAO

Project/src/data_access/calculatePlayerAverage/meanPlayerCalculator.java, Project/src/data_access/calculatePlayerAverage/playerCalculator.java, Project/src/data_access/calculatePlayerAverage/rangePlayerCalculator.java
note: put in data_access package since was unsure where else i should put it, feel free to move it to wherever it makes the most sense (however please lmk beforehand so that I am not working on the file while it happens)
(1) created the regular "meanCalculator", which is effectively the same as what was in the player and team entities. however, we can make it s.t. both player and team use those classes instead of separately creating.
(2) made it return "Object" since for the one with range will not return a single int and was unsure of a better way, let me know if there's a better method.
(3) began implementation of "rangeCalculator". it's a bit more complicated than regular mean and I'm working on setup for it atm, hence the PR right now. Will update when fully completed.
=> most of strategy design pattern

Project/src/interface_adapter/bet_recommendation/RecommendController.java, Project/src/interface_adapter/bet_recommendation/RecommendPresenter.java, Project/src/interface_adapter/bet_recommendation/RecommendState.java, Project/src/interface_adapter/bet_recommendation/RecommendViewModel.java, Project/src/use_case/bet_recommendation/RecommendationInputData.java, Project/src/use_case/bet_recommendation/RecommendationInteractor.java, Project/src/use_case/bet_recommendation/RecommendationOutputBoundary.java, Project/src/view/BetRecommendView.java
Completed the use case for bet recommendation, modified the input data and output data so it takes in the first and last name of the player, completed the use case interactor , just need the use case factory to be done
=> Implemented interactor for recommendation use case

Project/src/interface_adapter/player_bets/PlayerController.java, Project/src/interface_adapter/player_bets/PlayerPredictionState.java, Project/src/interface_adapter/player_bets/PlayerPredictionViewModel.java, Project/src/interface_adapter/player_bets/PlayerPresenter.java, Project/src/use_case/player_bet_predictor/PlayerInputBoundary.java, Project/src/use_case/player_bet_predictor/PlayerInputData.java, Project/src/use_case/player_bet_predictor/PlayerInteractor.java, Project/src/use_case/player_bet_predictor/PlayerOutputBoundary.java, Project/src/use_case/player_bet_predictor/PlayerOutputData.java, Project/src/view/PlayerView.java
added buttons, titles, etc. for player point prediction use case. 
still have yet to set it up in our app
=> set up player interface adapters

Project/src/data_access/PlayerDataAccessObject.java, Project/src/entity/Player.java, Project/src/use_case/player_bet_predictor/PlayerInteractor.java
reverted dao so that recommendation interactor works, re-did player interactor so that it still works as needed.
=> reverted dao and fixed player interactor accordingly

.idea/modules.xml, Project/src/entity/BetHistory.java, Project/src/use_case/bet_predictor/BetInteractor.java, Project/src/view/BetPredictionView.java
Bethistroy method setbethistory modified so that it saves the first bet made.
=> Fixed bethistory not saving first bet

Project/src/interface_adapter/bet_prediction/BetPredictionViewModel.java, Project/src/interface_adapter/menu/MenuPresenter.java, Project/src/use_case/menu/MenuInteractor.java, Project/src/view/BetRecommendView.java
- description for input description text area was too large, and overlapping with actual input section
- Edited bet recommend view to fix bug
- input text area was also editable
- Fixed menu presenter bug introduced from merging
- Edited bet prediction view model values
=> Fix recommend view

.idea/modules.xml, Project/src/app/Main.java, Project/src/app/MenuUseCaseFactory.java, Project/src/app/PlayerUseCaseFactory.java, Project/src/data_access/PlayerDataAccessObject.java, Project/src/interface_adapter/menu/MenuController.java, Project/src/interface_adapter/menu/MenuPresenter.java, Project/src/interface_adapter/menu/MenuViewModel.java, Project/src/interface_adapter/player/PlayerController.java, Project/src/interface_adapter/player/PlayerPresenter.java, Project/src/interface_adapter/player/PlayerState.java, Project/src/interface_adapter/player/PlayerViewModel.java, Project/src/use_case/menu/MenuInputBoundary.java, Project/src/use_case/menu/MenuInteractor.java, Project/src/use_case/menu/MenuOutputBoundary.java, Project/src/use_case/player/PlayerDataAccessInterface.java, Project/src/use_case/player/PlayerInputBoundary.java, Project/src/use_case/player/PlayerInputData.java, Project/src/use_case/player/PlayerInteractor.java, Project/src/use_case/player/PlayerOutputBoundary.java, Project/src/use_case/player/PlayerOutputData.java, Project/src/use_case/player/calculatePlayerAverage/Context.java, Project/src/use_case/player/calculatePlayerAverage/meanPlayerCalculator.java, Project/src/use_case/player/calculatePlayerAverage/playerCalculator.java, Project/src/use_case/player/calculatePlayerAverage/rangePlayerCalculatorOverlap.java, Project/src/use_case/player/calculatePlayerAverage/sampleCalculation.java, Project/src/use_case/player_bet_predictor/PlayerTeamDataAccessInterface.java, Project/src/view/MenuView.java, Project/src/view/PlayerView.java
- Refactored player packages and files for consistency
- Created player use case factory
- implemented player view styling
- edited player view model for added text
- fix player bet name in view model and view
- Modified menu factory to pass player view model
- Modified input and output boundaries, controller, interactor, and presenter, to open player view
- Added player button and button listeners in menu view
=> Set up player view 

Project/src/entity/BetHistory.java, Project/src/interface_adapter/bet_prediction/BetPredictionPresenter.java, Project/src/interface_adapter/bet_recommendation/RecommendController.java, Project/src/use_case/bet_predictor/BetInteractor.java, Project/src/use_case/bet_recommendation/RecommendationInputBoundary.java, Project/src/use_case/bet_recommendation/RecommendationInputData.java, Project/src/use_case/bet_recommendation/RecommendationInteractor.java, Project/src/view/BetRecommendView.java
Added support to bethistory for recommendations, cleaned up the displayhistory string that is viewed by the user showing them their bethistory. Made bethistory extendable to future use case's
=> Changes to bethistory to extend it to reccomendations

Project/src/use_case/bet_recommendation/RecommendationInteractor.java
swapped risky and safer bets since they previously logically did not make sense (mainly name, does not affect software architecture)
=> fixed names for recommendationinteractor

Project/src/use_case/bet_recommendation/RecommendationInteractor.java
previously had overlap, fixed by swapping necessary methods
=> fixed function swap for RecommendationInteractor

Project/src/view/BetHistoryView.java
- edit bet history view to make it scrollable
- fixed bet history text is editable
=> Make bet history scrollable

Project/test/interactorTest/LoginTest.java, pom.xml
=> completed tests for login interactor
